### ISSUE TITLE
hello, is this module functional for godot 3.5?

### ISSUE THREAD

**Issue by undersky23** [funexpected/godot-spine-module#5]
I'm trying to install your module but I use godot version 3.5 and I'm having trouble compiling it

**Comment by jkb0o** [comment]
I've pushed some fixes and added [installation](https://github.com/funexpected/godot-spine-module#installation) section to readme. Now module compiles and runs well with Godot 3.5. Fill free to reopen this if fix doesn't help.

**Comment by ghost** [comment]
> I've pushed some fixes and added [installation](https://github.com/funexpected/godot-spine-module#installation) section to readme. Now module compiles and runs well with Godot 3.5. Fill free to reopen this if fix doesn't help.

thank you, I am also interested in the flash plugin. Could you port it to 3.5 as well? 🥰
